# Generated by Django 5.0.1 on 2024-01-29 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('block_lot', models.CharField(blank=True, max_length=10, null=True)),
                ('block', models.CharField(blank=True, max_length=10, null=True)),
                ('lot', models.CharField(blank=True, max_length=10, null=True)),
                ('fire_prevention_district', models.IntegerField(blank=True, null=True)),
                ('police_district', models.IntegerField(blank=True, null=True)),
                ('supervisor_district', models.IntegerField(blank=True, null=True)),
                ('neighbourhood', models.IntegerField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permit', models.CharField(max_length=50)),
                ('cnn', models.CharField(blank=True, max_length=20, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('REQUESTED', 'REQUESTED'), ('SUSPEND', 'SUSPEND'), ('EXPIRED', 'EXPIRED')], max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_coordinates', to='core.coordinates')),
                ('food_items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='core.food')),
            ],
        ),
    ]
